//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontGen_iOS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontGen_iOS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;ConsentText&lt;/key&gt;
        ///	&lt;dict&gt;
        ///		&lt;key&gt;default&lt;/key&gt;
        ///		&lt;string&gt;FontGen_iOS is not responsible for any damage on your device if something bad really happens. FontGen_iOS 不会对 iOS 的可能存在的潜在设备伤害负责。&lt;/string&gt;
        ///	&lt;/dict&gt;
        ///	&lt;key&gt;PayloadContent&lt;/key&gt;
        ///	&lt;array&gt;
        ///		&lt;dict&gt;
        ///			&lt;key&gt;Font&lt;/key&gt;
        ///			&lt;data&gt; 的本地化字符串。
        /// </summary>
        internal static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/data&gt;
        ///			&lt;key&gt;Name&lt;/key&gt; 的本地化字符串。
        /// </summary>
        internal static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;key&gt;PayloadDescription&lt;/key&gt;
        ///			&lt;string&gt;Configures Font setting/配置字体设置&lt;/string&gt;
        ///			&lt;key&gt;PayloadDisplayName&lt;/key&gt;
        ///			&lt;string&gt;Fonts/字体&lt;/string&gt;
        ///			&lt;key&gt;PayloadIdentifier&lt;/key&gt;
        ///			&lt;string&gt;com.apple.font.%FontPayloadUUID%&lt;/string&gt;
        ///			&lt;key&gt;PayloadType&lt;/key&gt;
        ///			&lt;string&gt;com.apple.font&lt;/string&gt;
        ///			&lt;key&gt;PayloadUUID&lt;/key&gt;
        ///			&lt;string&gt;%FontPayloadUUID%&lt;/string&gt;
        ///			&lt;key&gt;PayloadVersion&lt;/key&gt;
        ///			&lt;integer&gt;1&lt;/integer&gt;
        ///		&lt;/dict&gt;
        ///	&lt;/array&gt;
        ///	&lt;key&gt;PayloadDescription&lt;/key&gt;
        ///	&lt;string&gt;Install Font on your iOS Device [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string H3 {
            get {
                return ResourceManager.GetString("H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;key&gt;PayloadOrganization&lt;/key&gt;
        ///	&lt;string&gt;FontGen_iOS&lt;/string&gt;
        ///	&lt;key&gt;PayloadRemovalDisallowed&lt;/key&gt;
        ///	&lt;false/&gt;
        ///	&lt;key&gt;PayloadType&lt;/key&gt;
        ///	&lt;string&gt;Configuration&lt;/string&gt;
        ///	&lt;key&gt;PayloadUUID&lt;/key&gt;
        ///	&lt;string&gt;%ProfilePayloadUUID%&lt;/string&gt;
        ///	&lt;key&gt;PayloadVersion&lt;/key&gt;
        ///	&lt;integer&gt;1&lt;/integer&gt;
        ///&lt;/dict&gt;
        ///&lt;/plist&gt; 的本地化字符串。
        /// </summary>
        internal static string H4 {
            get {
                return ResourceManager.GetString("H4", resourceCulture);
            }
        }
    }
}
